### ISSUE TITLE
Failed Context Types: Required context `redux` was not specified in `Connector`

### ISSUE THREAD

**Issue by deowk** [gaearon/redux#238]
Hi,

I am getting the following error 

```
Warning: Failed Context Types: Required context `redux` was not specified in `Connector`. Check the render method of `Layout`.
TypeError: Cannot read property 'subscribe' of undefined
    at new Connector (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/redux/lib/components/createConnector.js:43:39)
    at ReactCompositeComponentMixin.mountComponent (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactCompositeComponent.js:135:16)
    at wrapper [as mountComponent] (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactCompositeComponentMixin.mountComponent (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at wrapper [as mountComponent] (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactCompositeComponentMixin.mountComponent (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at wrapper [as mountComponent] (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (/Users/deowardkotze/grad_connection/cc/campus/src/react-client/node_modules/react/lib/ReactReconciler.js:38:35)
```

The strange thing is that everything in the Layout component is working and the state is changing when I fire actions as expected. This is how layout component looks.

```
"use strict";

var React = require("react");
var Navigation = require("./navigation.js");
var Footer = require("./footer.js");
import * as LoginActions from "../actions/LoginActions";
import { bindActionCreators } from "redux";
import { Connector } from "redux/react";

function select(state) {
  return {userLoggedIn: state.loginstore.userLoggedIn};
}

export default class Layout extends React.Component {

  render() {
    return (
      <html>
        <head>
         ..........
        </head>
        <body>
            ..........
            <Connector select={select}>
              {({userLoggedIn, dispatch}) =>
                <Navigation userLoggedIn={userLoggedIn} {...bindActionCreators(LoginActions, dispatch)}/>
              }
            </Connector>

            {this.props.children}

            <Footer />
        </body>
        <script src="/public/client.min.js"></script>
      </html>
    );
  }
}
```

and I am including redux like this

```
export default class App extends React.Component {
  render() {
    const redux = createRedux(Client, this.props.initialState);
    return (
        <Provider redux={redux}>
        {() =>
          <Layout {...this.props} >
            <Router.RouteHandler {...this.props} />
          </Layout>
        }
        </Provider>
    );
  }
}
```

Why would I be getting this error even though everything seems to be working fine?

**Comment by emmenko** [comment]
One thing first: `redux` instance should be initialized once and not in the `render` method. Also, why are you rendering the all `html` in the `Layout` component?

PS: which version are you using?

**Comment by deowk** [comment]
@emmenko : I am using react-engine to render my components server-side and I am using JSX for my templates so that the reason all my html is in `Layout`, the way react-engine works is that it passes all the initial data from server side to the client side components through props and it was the easiest way for met to get hold of the initialState so I can rehydrate the client-side stores. My current version of redux is ^0.12.0 (thats the way it's listed in package.json). Would it preferable to instantiate the redux instance outside of a component and if so why?

**Comment by deowk** [comment]
@emmenko: Ok I solved this issue by moving my `stateful` components out of `Layout` - so they form part of `{this.props.children}`, going to close this since it's not really  an issue with redux but rather a specific use-case when used in conjunction with `react-engine`.

**Comment by emmenko** [comment]
@deowk sorry, been busy yesterday. Haven't used `react-engine` before, so I can't tell exactly what the problems was. Glad you managed to solve it.

**Comment by deowk** [comment]
@emmenko : I would be keen to add an example based on the counter or todo apps...I would like to contribute even if it's running tests or any other tasks you guys might require.

**Comment by emmenko** [comment]
You mean with `react-engine`?

**Comment by deowk** [comment]
Yeah so examples with `redux + react-engine`

**Comment by emmenko** [comment]
Sure, just create your own repo and when it's ready we can link it from the README.
