### ISSUE TITLE
spawnSync TypeError: Incorrect value for stdio stream when running build:examples

### ISSUE THREAD

**Issue by kevinold** [gaearon/redux#438]
I'm running into the following issue on the breaking-changes-1.0 and rewrite-docs-again branches.

I'm see the issue on 0.10.38, 0.12.1 and 0.12.7.
```
➜  redux git:(breaking-changes-1.0) npm run build:examples

> redux@1.0.0-rc build:examples /Users/kevinold/github_clones/redux
> babel-node examples/buildAll.js

npm WARN package.json counter-redux@0.0.0 No README data
react-redux@0.4.0 node_modules/react-redux
└── invariant@2.1.0 (envify@3.4.0)
Hash: 2ce3631c7bc37d1beef0
Version: webpack 1.10.5
Time: 2953ms
    Asset    Size  Chunks             Chunk Names
bundle.js  981 kB       0  [emitted]  main
   [0] multi main 64 bytes {0} [built]
    + 258 hidden modules
child_process.js:941
      throw new TypeError('Incorrect value for stdio stream: ' +
            ^
TypeError: Incorrect value for stdio stream: { type: 'fd', fd: { type: 'fd', fd: 0 } }
    at child_process.js:941:13
    at Array.reduce (native)
    at _validateStdio (child_process.js:865:17)
    at Object.spawnSync (child_process.js:1287:19)
    at Object.<anonymous> (/Users/kevinold/github_clones/redux/examples/buildAll.js:7:10)
    at Module._compile (module.js:460:26)
    at normalLoader (/Users/kevinold/github_clones/redux/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kevinold/github_clones/redux/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

Looks related to this https://github.com/joyent/node/issues/9158

Submitting a PR soon to get past this.

**Comment by gaearon** [comment]
Isn't this a Babel issues rather than ours?

**Comment by gaearon** [comment]
Closing as you fixed it in #439. Thanks!

**Comment by kevinold** [comment]
I discovered that if I installed io.js 3.0.0 that there were no issues and when running the counter and todo examples, io.js is required for the tests to run (jsdom requirement) when running "npm run build:examples".  I see from .travis.yml now that you're running io.js, so I wondering if an enforcement via package.json or just a readme note would help those in the near future.

**Comment by gaearon** [comment]
It's something for a “Contributing” doc we don't currently have.
